apiVersion: v1
kind: Service
metadata:
  name: ml-flask-service
spec:
  type: NodePort
  selector:
    app: ml-flask
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007  # Accessible via <minikube_ip>:30007
